ini.go, ini_test.go
增加HasValue的目的是我在使用Peach的时候，toc.ini都是自增键值，所以只用到Value，而且每个分区下的值应该是唯一的，所以如果用程序添加一个文章那么需要判断是否存在这个值。HasValue没有判断子分区是因为我觉得不同子分区内可以有相同的值。
=> 新增HasKey和HasValue方法，用来判断键或值是否存在。

ini.go, ini_test.go
This commit changes `Section.Haskey` to `Section.HasKey` (notice the capitalization on the k), which is what the documentation states (and which reflects the naming convention for this library). There is also a very minor documentation fix for `Section.HasValue`.
=> Make method name Section.HasKey match documentation.

ini.go, ini_test.go
This adds support for comments on the end of section headers, e.g.
[a_section] ; A comment
It also fixes a couple of places where only `#` comments were supports - not `;` comments.
Test cases are included (they pass).
This closes bug #23
=> Better comments support

README.md, README_ZH.md, ini.go
`y`/`n` are also used as boolean values sometimes, extending
the library to infer these values for parseBool as well.
Tested manually through editing BOOL/BOOL_FALSE in ini_test.go.
cc: @Unknwon
=> Add `y`/`n` as options for BOOL values

ini.go, ini_test.go
I found that methods that return lists (Float64s, Ints, Int64s and etc.) do not handle parsing errors. For example, following code:
```go
config, _ := Load([]byte(_CONF_DATA))
stringKey := config.Section("array").Key("STRINGS")
fmt.Printf("string values: %v\n", stringKey.Strings(","))
fmt.Printf("float values: %v\n", stringKey.Float64s(","))
```
gives such result:
```
string values: [en zh de]
float values: [0 0 0]
```
I think that the best solution would be to return error from these methods, but it will break down back compatibility of interface.
Therefore I propose do not append to list such values, that was parsed with error.
=> Exclude not parsed values from lists.

ini.go, ini_test.go
A common practice in applications development is to allow the user
to customise/extend program's settings by overriding global defaults
set in system-wide config files (typically installed under /etc)
with site-specific copies (e.g. /usr/local/etc) and user-specific
files generally stored in the user's home directory. It must be
noticed that this cascade approach allows the user to specify only
those options that he wishes to override, whilst the other values
will keep their value already set in the other configuration
files. In general, when a program couldn't find any configuration
file rather than crashing it falls back to hardcoded default values.
These changes introduce a new function LooseLoad that allows the
caller to pass a slice of filenames without worrying about their
existence …
=> Add LooseLoad - fix #33

ini.go
Adds support for explicitly writing a header for the DEFAULT section in files. Disabled by default, and can be enabled by setting the following in the implementation of the library:
```
ini.DefaultHeader = true
```
For example:
```
package main
import (
"github.com/go-ini/ini"
)
func main() {
ini.DefaultHeader = true
cfg, _ := ini.Load("config.ini")
key := cfg.Section("DEFAULT").Key("key1")
key.SetValue("value2")
cfg.SaveTo("config.ini")
}
```
Closes #37
=> Add support for explicitly writing a header in the DEFAULT section

key_test.go, section.go
This PR lets us retrieve a list of parent keys that are
available to the child section.
=> Retrieve parent keys available to a child section

README.md, README_ZH.md
It looks like a typo in README's. I also verified the correct call in `key_test.go`.
=> Fix calls for KeysHash() in README files

ini.go, ini_test.go
The alignment length calculation did not take into account that
keys may be added to if they contained "\"", "=", ":", or "`".
This gave an under calculation and resulted in index out of
bounds when this happened to be the longest key.
Please feel free to give any feedback or issues with the following request
=> Fix panic from incorrect alignment length calculation

parser.go
I have a config.ini where section names can contain "]", which leads to parse
errors. While proper support for quoting would be best (issue #32) simply
matching the last "]" rather than the first helps in this case.
=> Match last ] in line when parsing Section header

struct.go, struct_test.go
Closes #59
The `isEmptyValue` is shamelessly stolen from https://github.com/golang/go/tree/master/src/encoding/json , I just added support for `time.Time`. 😉
=> Add support for omitempty tag option

README.md, ini.go, key.go
This PR lets you transform value with a mapping function. 
It let's you e.g. read a .ini file and expand all ${NAME} in a value with the names value from the environment via `os.ExpandEnv` as `ValueMapper`.
=> add value expander

struct.go, struct_test.go
omitempty must be ignored when unmarshalling into a struct, so that the
key name is parsed correctly.
=> Support omitempty in tags during MapTo

ini.go, ini_test.go, parser.go, section.go, section_test.go, testdata/aicc.ini
There are public standards ( example: https://github.com/ADL-AICC/AICC-Document-Archive/releases/tag/cmi001v4 ) that are based around INI formats that allow for both standard key/value sections as well as sections that contain raw data that cannot be parsed.  My attempt here is to provide a mechanism for leaving unparsed sections in their raw form, while otherwise meeting the INI parsing standards.  It's off by default and can only be opted-into on a per-section basis by section name as part of the LoadOptions config.  Tests included, and also cover the case-insensitive section names.
=> Added support for unparseable sections.

ini.go, ini_test.go, parser.go
I would have loved to provide as well a patch... 
I'll try, but maybe someone else is faster than me
here is a unit test that properly isolates the problem
=> boolean keys do not get sanitised from the \n

README.md
Section has GetKey function, and not config pointer directly.
```
cmd/export.go:32: cfg.GetKey undefined (type *ini.File has no field or method GetKey)
```
=> Config pointer does not have GetKey directly

ini.go
Some slight refactoring to avoid writing/renaming a temp file when writing a ini file. Using a temp file is problematic if the file you are writing to is mounted inside a Docker container (see https://github.com/go-gitea/gitea/issues/2197).
=> Avoid using temp file during write

struct.go, struct_test.go
Hi,
If I map a section to a struct with StrictMapTo instead of MapTo then fields with slice type are not mapped due to an 'if isStrict { return err}' construct in setSliceWithProperType. 
The PR is correcting this.
-ptr-
=> map slices in strict mode too

ini_test.go, key.go, key_test.go, section_test.go
Use backslash to escape delimiters.
Fixes #32
=> Escape delimiters in string slice values

struct.go, struct_test.go
time.Duration conversion in 32 bits systems. If duration is less than 16m50s the conversion will fail.
Yes
=> Fix integer overflow

key.go
NAME = ini
[package]
NAME = $(NAME)
I believe NAME in section [package] should evaluate to ini
nope :/
=> Keys should not consider themself for transformation.

file.go, ini.go
The default git config format is equivalent to PrettyFormat w/o
alignment (i.e. just spaces around '=') and SaveToIndent(..., "\t")
This patch allows for setting PrettyFormat=false and PrettySpaces=True
to achieve the same output as the git config default.
It is backwards compatible in that current use case output will not be
affected unless you specifically disable PrettyFormat AND enable
PrettySpaces.
=> Add Support for spaces around '=' w/o PrettyFormat

ini.go, ini_test.go, parser.go
Edge case has a value that contains an inline symbol such as `;` or `#`.
Currently parsing a value such as:
```
value = val#ue
```
would result into just `val` if `IgnoreInlineComment` is false.
If `IgnoreInlineComment` is true it would result into the full value, but it's incorrect to depend on this.
With the fix value would be parsed as `val#ue`.
Yes
@Unknwon
=> Fix inline value parsing

file.go, ini.go
Add option to have padding spaces around equal sign when PrettyFormat is disabled #161
eg:
> ini.PrettyFormat = false
>         ini.DefaultFormatLeft = "  "
>         ini.DefaultFormatRight = " "
=> Feature-#161-Add-DefaultFormat

section.go
Section's `DeleteKey()` method does not update the internal hash map.
No, wasn't sure whether to add it to `KeyHash`, `DeleteKey`, or as a separate test. Current behavior:
```go
package main
import (
"fmt"
"github.com/go-ini/ini"
)
func main() {
s := ini.Empty().Section("")
s.Key("key").SetValue("value")
fmt.Println("keys:", s.KeyStrings())
fmt.Println("hash:", s.KeysHash())
s.DeleteKey("key")
fmt.Println("keys:", s.KeyStrings())
fmt.Println("hash:", s.KeysHash())
}
```
Output:
```
keys: [key]
hash: map[key:value]
keys: []
hash: map[key:value]
```
=> section: update keysHash in DeleteKey

key.go, key_test.go
`strings.TrimRight(noption, ")s")` will strip strings that end in "s)s" which wasn't intended.  We should only string the first 2 characters and last two characters of the string since we know they will be "%(" and  ")s".
yes
=> Fix recursive char stripping when parsing recursive values

key.go, key_test.go, testdata/TestFile_WriteTo.golden, testdata/full.ini
parse hex number on map to struct, for example: 
ini file:
```ini
[Meter]
addr = 0x3000
```
map to:
```golang
type Meter struct{
Addr int `ini:"addr"`
}
```
=> parse hex number

struct.go, struct_test.go
Allow 'mapTo' to load into fields that are struct pointers iff there is
a section for that field and fieldname. The field is initialised to
pointer type and then the data is loaded.
Yes.
=> struct: map into fields that are struct pointers

ini_test.go, parser.go
Multline line values whose initial line was empty were not parsed. This style of list is commonly used in a couple of places, but the main one I've found is LLVMBuild.txt (an ini-style build configuration used by LLVM).
Yes
=> support Python multi-line values with empty first line

struct.go, struct_test.go
go-ini support `bool` but not `*bool` which is a clever way to work around the infamous `bool,omitempty` issue that Go serialization has. Then, a three state value exists.
```ini
Optional =
Optional = true
Optional = false
```
Needs for the editorconfig, https://github.com/editorconfig/editorconfig-core-go/pull/16 Even though, I might not be the correct way to handle the `unset` option.
Indeed. I should probably add more. Any pointers are appreciated.
=> struct: support for *bool

ini_python_multiline_test.go, parser.go, struct.go, struct_test.go
Unmashalling to a pointer field facilitates distinguishing between a key being undefined and being defined with the type's zero value. This is useful for cases where an application defines a default value, which is not the type's zero value and the config should be able to set the field value to the type's zero value.
This feature was already supported for `*bool` - I have extended the capability to all of the supported basic types.
Yes, I have extended the existing test to cover all of the new types.
=> parser: support unmashalling to all basic type pointers

README.md, file.go, file_test.go, ini.go
See https://github.com/go-ini/ini/pull/203
I just added a test for the closed PR and also fixed a bug (the default delimiter was set to '' it should be '=')
I also renamed the configuration to KeyValueDelimiterOnWrite as you suggested.
=> file: customize output delimiter

struct.go, struct_test.go
=> struct: ignore unexported fields when reflect

struct.go, struct_test.go
The problem in #241
Yes, I added a test case for the case pointed out in the issue #241 by tevino.
=> struct: correctly mapping non unique sections to slice field

file.go, file_test.go
fix  #252
Fix deleting the default section makes the next section inaccessible.
Yes,here are some test cases.
=> file: fix deleting the default section makes the next section inaccessible

file.go, ini.go, ini_test.go, section.go
No problem exists.  This feature is useful to me, and maybe to others:  allowing to specify an alternative delimiter (instead of ".") for separating child section name components.
ini: added option for ChildSectionDelimiter
file: added default for ChildSectionDelimiter (".") to maintain current behavior by default
section:
- append ChildSectionDelimiter instead of "." when checking if each section name begins with prefix
- use ChildSectionDelimiter instead of "." when checking for LastIndex of delimiter
Yes, the new feature is tested.
=> Allow alternative delimiter for child sections

file.go, file_test.go, ini.go, ini_test.go
Short-circuit load #180
1. The ShortCircuit option is adde
2. A judgment is added to the Reload() method to implement short-circuit load.
Note: When ShortCircuit and Loose are both true, ShortCircuit has priority over Loose.
Yes, all CI pass the test.
=> Support Short-circuit load

struct.go, struct_test.go
Allow embedded structs to inherit from the same ini section.
```go
type Base struct {
Inherited bool
}
type Extended struct {
Base `ini:",,,,extends"`
Extended bool
}
```
```ini
[section]
Inherited=true
Extended=true
```
Yes
Signed-off-by: Andrew Thornton <art27@cantab.net>
=> Add extends functionality to allow embedded fields

ini.go, key.go, key_test.go
Copied from #285 since I don't seem to be able to change the target of that one.
Fixes #284.
Test cases have been added to key_test.go for both the default and new cases.
=> key: add `AllowDuplicateShadowValues` option

file_test.go, helper_test.go, ini_python_multiline_test.go, ini_test.go, key_test.go, parser_test.go, section_test.go, struct_test.go
Fixes #295
This PR is about refactoring tests, no additional tests are necessary.
This is an attempt to refactor tests into using testify instead of goconvey.
During the refactor I followed the following rules:
- Singular top level `Convey` was removed everywhere
- Multiple `Convey` blocks were converted into subtests (`t.Run`)
- Child `Convey` blocks were converted into subtests (`t.Run`)
- `require` was used everywhere when the following assertions depended on the outcome (eg. no error or no nil return value)
- `assert` was used everywhere else
I suggest turning off showing whitespaces in the diff because there are lots of indentation changes.
If you like the result, I can refactor the remaining tests as well.
=> all: rewrite tests to use testify instead of goconvey

ini_test.go, parser.go, testdata/multiline.ini
This PR fixes parsing Python multiline strings to keep the original indentation instead of removing all leading spaces. It breaks some compatibility with legacy Python parsers as them fail to parse multiline strings that are malformed. This issue was first reported [here](https://github.com/wakatime/wakatime-cli/issues/532).
Yes
=> Fix parsing python multiline string

file.go, file_test.go
copied implementation from section.go
Feature proposal #271.
Yes indeed (after seeing this question, but I digress).
=> file: add `HasSection` method

ini_test.go, parser.go, testdata/multiline_eof.ini
When parsing `python multiline` values and the key which is being parsed is the last one on the ini file and there's no new line at the end, then it throws an error. To fix that we might not consider EOF as an error when reading the last line because it's either can be a `\n` or `EOF`.
This problem was first reported [here](https://github.com/wakatime/wakatime-cli/issues/593).
The `TestPythonMultiline_EOF` was added.
=> Fix python multiline EOF error

ini_test.go, parser.go
When configured with `AllowNestedValues: true`, the parser attempts to parse values "nested" under a key, [AWS-style](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#nested-values). To trigger this behavior, the parent key must have an empty value, and child keys must be indented. However, if the next value is in a different section, it cannot be a nested value, but the parser can treat it as such anyways. As an example:
```
[section]
key1 = value1
key2 =
[section2]
key3 = value3
```
Before this PR, `key3` is treated as a nested value under `key2`, and `section2` has no keys. 
Yes, I've added tests that cover the issue and fail on the current tip of `main`.
=> Fix nested values can span sections

.editorconfig, file.go, key.go, key_test.go
When there are no value for a given key, ValueWithShadows used to return an array containing an empty string. Instead, this PR makes it return an empty array. This change produces the same behaviour for StringsWithShadows as it uses ValueWithShadows to do it's job.
Link to the issue: https://github.com/go-ini/ini/issues/310
There aren't any existing test cases for ValueWithShadows. Should I add a new one ?
PS: I tried to wait a little before doing the PR in case any newcomer wanted to use the opportunity of this simple fix for their first PR, but it's been a month now so I'll  just do it myself ¯\\\_(ツ)_/¯
=> Return an empty array from `ValueWithShadows` if there is none

key.go, key_test.go
Empty values of shadow keys are ignored in the returned list of `ValueWithShadows`.
Link to the issue: https://github.com/go-ini/ini/issues/294
=> key: ignore empty values in `ValueWithShadows`

file.go, file_test.go, ini_test.go, key_test.go, struct_test.go, testdata/TestFile_WriteTo.golden
This PR should prevent a double new line to be written when rendering the last section.
=> write: pretty print section only if it is not the last one

.github/workflows/go.yml, .golangci.yml, README.md, codecov.yml
=> chore: various config updates to CI

error.go, ini_test.go, parser.go
This PR fixes a scenario where the key name is zero length and `readKeyName` incorrectly handle it. Even if setting `SkipUnrecognizableLines` to **true** wasn't being skipped.
=> parser: fix line skipping when key is empty

deprecated.go, ini.go
Changed the DefaultSection constant to a variable so that it may be altered for use with AWS cli configs.
Link to the issue: https://github.com/go-ini/ini/issues/287
=> ini: allow changing the default section name
